name: conan/bjam
on: [push]
env:
  BUILD_TYPE: Release # Release, Debug, RelWithDebInfo, etc.
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-2016] #, macOS-latest] #fails because of SetupHunter - version not present, although first time build succeeded - why ???

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create Build Environment
      #shell: bash # ON W$ FOR SOME F.REASON using bash in this step causes a failure in configure step
      run: |
       python -m pip install --upgrade pip
       pip3 install wheel setuptools 
       pip3 install conan

    - name: Cache Conan
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-bjam
      with:
        path: ~/.conan/
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }} #key: ${{ runner.os }}-
        restore-keys: |
          ${{ matrix.os }}-build-${{ env.cache-name }}-
          ${{ matrix.os }}-build-
          ${{ matrix.os }}-

    - name: Configure bjam
      shell: bash # MUST BE BASH TO SUCCEED!!! Use a bash shell so we can use the same syntax for environment variable access regardless of the host operating system
      working-directory: ${{runner.workspace}} #/build
      run: |
              conan install -if "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE" # -DCMAKE_BUILD_TYPE=$BUILD_TYPE 
              echo $GITHUB_WORKSPACE
              ls -l $GITHUB_WORKSPACE
              echo ${{runner.workspace}}
              ls -l ${{runner.workspace}}
              #conan build --configure . # $BUILD_TYPE

    - name: Build
      working-directory: $GITHUB_WORKSPACE # ${{runner.workspace}} #/build
      shell: bash # the step fails if missing!
      run: conan build -if "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE" # $BUILD_TYPE # You can specify a specific target with "--target <NAME>"

    - name: Test
      working-directory: ${{runner.workspace}} #/build
      shell: bash
      run: conan build --test $GITHUB_WORKSPACE
